server: 
  port: 9000


#2nd way of security approac
# spring:  security:    user:     name: skh
#                                  password: skhskh 
spring:
  security: 
    user:
      name: skh
      password: skhskh 
      
      
#  sql: 
#    init: 
#      data-locations: classpath:data.sql
  application: 
    name: h2-demo
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    properties:
      hibernate: 
        format_sql: true # To format the quries on console.
#    defer-datasource-initialization: true
    show_sql : true
    spring.jpa: 
      database-platform: org.hibernate.dialect.H2Dialect

